name: cd

on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Get triggering workflow tag
        run: echo "TAG=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Download Docker Image Tag from previous run (better way)
        uses: actions/github-script@v7
        id: get-tag
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            const tag = run.data.head_branch;
            core.setOutput('tag', tag);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug tag
        run: echo "Docker tag: ${{ steps.get-tag.outputs.tag }}"


      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/personal-website:${{ steps.get-tag.outputs.tag }}

      - name: Delete old container
        run: docker rm -f personal-website || true

      - name: Run Docker container
        run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/personal-website:${{ steps.get-tag.outputs.tag }}
