name: Docker Image CI

on:
  push:
    tags:
      - 'v*'  # Only run on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker tag
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t ${{ env.TAG }} .

      - name: Push the Docker image
        run: docker push tyudosen/personal-website:${{ env.TAG }}
